development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  username: 
  password: